[package]
name = "colors-test"
version = "0.1.0"
authors = ["Hyprcore Team"]
description = "A simple fragment to test color rendering"

[[templates]]
target = "~/.local/bin/hyprcore_test_colors"
content = """#!/usr/bin/fish
# Hyprcore Color Test
# Generated by colors_test.frag

echo "Testing Hyprcore Color Mappings..."
echo ""

{% for key, value in colors %}
# Remove # for set_color just in case, though fish supports it usually
set_color {{ value | replace(from="#", to="") }}
echo "{{ key }}: {{ value }}"
set_color normal
{% endfor %}

echo ""
echo "Done."
"""

[hooks]
reload = "chmod +x ~/.local/bin/hyprcore_test_colors"
