# Serena project configuration for hyprink
# hyprink is a Rust-based system-wide theming tool

languages:
- rust
- bash
encoding: "utf-8"

ignore_all_files_in_gitignore: true

ignored_paths:
- target/
- "*.lock"
read_only: false

excluded_tools: []

initial_prompt: ""

project_name: "hyprink"
included_optional_tools: []
fixed_tools: []
