/**
 * @file hcore.h
 * @brief HyprCore FFI Interface - C bindings for the HyprCore library
 * 
 * Provides a stable C-ABI interface for configuration management,
 * logging, packaging, and fragment processing.
 * 
 * @see https://github.com/ryugen/hyprcore
 */

#ifndef HCORE_H
#define HCORE_H

/* Compiler feature detection and hardening macros */
#if defined(__GNUC__) || defined(__clang__)
  #define HCORE_API __attribute__((visibility("default")))
  #define HCORE_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
  #define HCORE_NONNULL(...) __attribute__((nonnull(__VA_ARGS__)))
  #define HCORE_DEPRECATED(msg) __attribute__((deprecated(msg)))
  #define HCORE_PRINTF(fmt, args) __attribute__((format(printf, fmt, args)))
#elif defined(_MSC_VER)
  #define HCORE_API __declspec(dllexport)
  #define HCORE_WARN_UNUSED_RESULT _Check_return_
  #define HCORE_NONNULL(...)
  #define HCORE_DEPRECATED(msg) __declspec(deprecated(msg))
  #define HCORE_PRINTF(fmt, args)
#else
  #define HCORE_API
  #define HCORE_WARN_UNUSED_RESULT
  #define HCORE_NONNULL(...)
  #define HCORE_DEPRECATED(msg)
  #define HCORE_PRINTF(fmt, args)
#endif

/* Thread safety annotations (Clang only) */
#if defined(__clang__) && defined(__has_attribute)
  #if __has_attribute(capability)
    #define HCORE_CAPABILITY(x) __attribute__((capability(x)))
    #define HCORE_REQUIRES(...) __attribute__((requires_capability(__VA_ARGS__)))
    #define HCORE_EXCLUDES(...) __attribute__((locks_excluded(__VA_ARGS__)))
  #endif
#endif
#ifndef HCORE_CAPABILITY
  #define HCORE_CAPABILITY(x)
  #define HCORE_REQUIRES(...)
  #define HCORE_EXCLUDES(...)
#endif

/* Null pointer check helper */
#define HCORE_ASSERT_NOT_NULL(ptr) \
    do { if (!(ptr)) { return; } } while(0)
#define HCORE_ASSERT_NOT_NULL_RET(ptr, ret) \
    do { if (!(ptr)) { return (ret); } } while(0)

/* Generated with cbindgen:0.29.2 */

/* AUTO-GENERATED by cbindgen - DO NOT EDIT */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque context pointer (wraps HyprConfig with error storage)
 */
typedef struct HCoreContext HCoreContext;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct HCoreContext *hcore_context_new(void);

/**
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `HCoreContext` created by `hcore_context_new`.
 */
void hcore_context_free(struct HCoreContext *ctx);

/**
 * Copies the last error message into the provided buffer.
 * Returns the number of bytes written (excluding null terminator),
 * or -1 if the buffer was too small or no error exists.
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `HCoreContext` created by `hcore_context_new`.
 * * `buffer` must be a valid pointer to a writable memory region of at least `len` bytes.
 */
int hcore_get_last_error(struct HCoreContext *ctx, char *buffer, uintptr_t len);

/**
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `HCoreContext`.
 * * `level`, `scope`, and `msg` must be valid, null-terminated C strings.
 */
void hcore_log(struct HCoreContext *ctx, const char *level, const char *scope, const char *msg);

/**
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `HCoreContext`.
 * * `src_dir` and `out_file` must be valid, null-terminated C strings.
 */
int hcore_pack(struct HCoreContext *ctx, const char *src_dir, const char *out_file);

/**
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `HCoreContext`.
 * * `pkg_file` and `target_dir` must be valid, null-terminated C strings.
 */
int hcore_unpack(struct HCoreContext *ctx, const char *pkg_file, const char *target_dir);

/**
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `HCoreContext`.
 * * `path` must be a valid, null-terminated C string.
 */
int hcore_install(struct HCoreContext *ctx, const char *path);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

/* ABI version for runtime compatibility checks */
#define HCORE_ABI_VERSION_MAJOR 0
#define HCORE_ABI_VERSION_MINOR 2
#define HCORE_ABI_VERSION_PATCH 1

/* End of hcore.h */
#endif /* HCORE_H */
