/**
 * @file hyprink.h
 * @brief hyprink FFI Interface - C bindings for the hyprink library
 *
 * Provides a stable C-ABI interface for configuration management,
 * logging, packaging, and template processing.
 *
 * @see https://github.com/ryugen-io/hyprink
 */

#ifndef HYPRINK_H
#define HYPRINK_H

/* Compiler feature detection and hardening macros */
#if defined(__GNUC__) || defined(__clang__)
  #define HYPRINK_API __attribute__((visibility("default")))
  #define HYPRINK_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
  #define HYPRINK_NONNULL(...) __attribute__((nonnull(__VA_ARGS__)))
  #define HYPRINK_DEPRECATED(msg) __attribute__((deprecated(msg)))
  #define HYPRINK_PRINTF(fmt, args) __attribute__((format(printf, fmt, args)))
#elif defined(_MSC_VER)
  #define HYPRINK_API __declspec(dllexport)
  #define HYPRINK_WARN_UNUSED_RESULT _Check_return_
  #define HYPRINK_NONNULL(...)
  #define HYPRINK_DEPRECATED(msg) __declspec(deprecated(msg))
  #define HYPRINK_PRINTF(fmt, args)
#else
  #define HYPRINK_API
  #define HYPRINK_WARN_UNUSED_RESULT
  #define HYPRINK_NONNULL(...)
  #define HYPRINK_DEPRECATED(msg)
  #define HYPRINK_PRINTF(fmt, args)
#endif

/* Thread safety annotations (Clang only) */
#if defined(__clang__) && defined(__has_attribute)
  #if __has_attribute(capability)
    #define HYPRINK_CAPABILITY(x) __attribute__((capability(x)))
    #define HYPRINK_REQUIRES(...) __attribute__((requires_capability(__VA_ARGS__)))
    #define HYPRINK_EXCLUDES(...) __attribute__((locks_excluded(__VA_ARGS__)))
  #endif
#endif
#ifndef HYPRINK_CAPABILITY
  #define HYPRINK_CAPABILITY(x)
  #define HYPRINK_REQUIRES(...)
  #define HYPRINK_EXCLUDES(...)
#endif

/* Null pointer check helper */
#define HYPRINK_ASSERT_NOT_NULL(ptr) \
    do { if (!(ptr)) { return; } } while(0)
#define HYPRINK_ASSERT_NOT_NULL_RET(ptr, ret) \
    do { if (!(ptr)) { return (ret); } } while(0)

/* Generated with cbindgen:0.29.2 */

/* AUTO-GENERATED by cbindgen - DO NOT EDIT */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque context pointer (wraps Config with error storage)
 */
typedef struct HyprinkContext HyprinkContext;

/**
 * Opaque store wrapper
 */
typedef struct HyprinkStore HyprinkStore;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct HyprinkContext *hyprink_context_new(void);

/**
 * # Safety
 */
void hyprink_context_free(struct HyprinkContext *ctx);

/**
 * # Safety
 */
int hyprink_get_last_error(struct HyprinkContext *ctx, char *buffer, uintptr_t len);

/**
 * # Safety
 */
void hyprink_context_set_app_name(struct HyprinkContext *ctx, const char *name);

/**
 * # Safety
 */
void hyprink_log(struct HyprinkContext *ctx, const char *level, const char *scope, const char *msg);

/**
 * # Safety
 */
int hyprink_log_preset(struct HyprinkContext *ctx,
                       const char *preset_key,
                       const char *msg_override);

/**
 * # Safety
 */
int hyprink_pack(struct HyprinkContext *ctx, const char *src_dir, const char *out_file);

/**
 * # Safety
 */
int hyprink_unpack(struct HyprinkContext *ctx, const char *pkg_file, const char *target_dir);

/**
 * Applies a template file immediately to the current config context.
 * # Safety
 */
int hyprink_apply_file(struct HyprinkContext *ctx, const char *path);

/**
 * # Safety
 */
struct HyprinkStore *hyprink_store_load(const char *path);

/**
 * # Safety
 */
void hyprink_store_free(struct HyprinkStore *store);

/**
 * # Safety
 */
int hyprink_store_get_last_error(struct HyprinkStore *store, char *buffer, uintptr_t len);

/**
 * # Safety
 */
int hyprink_store_save(struct HyprinkStore *store);

/**
 * # Safety
 */
int hyprink_store_add_toml(struct HyprinkStore *store, const char *toml_content);

/**
 * # Safety
 */
int hyprink_store_remove(struct HyprinkStore *store, const char *name);

/**
 * # Safety
 */
int hyprink_store_count(struct HyprinkStore *store);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

/* ABI version for runtime compatibility checks */
#define HYPRINK_ABI_VERSION_MAJOR 0
#define HYPRINK_ABI_VERSION_MINOR 1
#define HYPRINK_ABI_VERSION_PATCH 1

/* End of hyprink.h */
#endif /* HYPRINK_H */
